const String apiKey = String.fromEnvironment('API_KEY');

List<String> roastUploadPrompts = [
  "Drop Ya Face Here 😭📸",
  "Let Me Cook U Real Quick 🔥👨‍🍳",
  "Upload the Mugshot 😭🚔",
  "Show Me That NPC Render 🤖📷",
  "Toss In Your Selfie, Victim 🙈🔥",
  "Enter the Roast Zone If You Dare 😤🔥",
  "Drop the Pic, I Need a Giggle 🤣📸",
  "Bring That Face to the Slaughterhouse 😭🔪",
  "Load Up Your Self-Esteem for Deletion 💀📸",
  "Hand Over the Selfie — For Science 🤓🧪",
  "Wanna Get Deep-Fried? 🍟🔥",
  "Show Me the Face You Warn Kids About 😭👹",
  "Let Me See That Walmart-Quality Selfie 📸💀",
  "Get In the Kitchen, I’m Preheated 🔥👨‍🍳",
  "Upload Your Face, Future L 😭📉",
  "Drop That Filtered Disaster 😭✨",
  "Come Get Digitally Bullied 🤣🔥",
  "The Roast Gods Demand a Sacrifice 🙏📸",
  "Show Me Ya Face, I Need Content 😭📱",
  "Drop the Selfie — No Backups Allowed 💀🔥",
  "Post Your Mugshot 📸💀",
  "Upload That Face — I’m Watching 👁️🔥",
  "Drop Selfie, Collect Tears 😭📱",
  "Show Me What I’ll Roast Next 🍗🔥",
  "Send Your Face — I Need Material 🤣📷",
  "Dare to Upload? I Dare to Destroy 😈🔨",
  "Face Drop Zone Ahead 🚧📸",
  "Let’s See That Face — No Filter Needed 😤📷",
  "Upload & Brace for Impact 💥📸",
  "Mugshot Boarding — All Selfies Welcome 🛫😈",
  "Load That Selfie — Brace Yourself ⚠️📱",
  "Send That Selfie — Watch Reality Bend 🔮📸",
  "Drop the Selfie — Accountability Time 😬📷",
  "Upload Your Face — I’m Hungry for Content 🍽️📸",
  "Show That NPC Face — I Need a Good Laugh 🤖🔥",
  "Bring Your Face, I’ll Bring the Roast 🔥📸",
  "Selfie Drop — Submit to the Flames 🔥📱",
  "Upload. Brace. Regret. 😭📷",
  "Selfie Upload — No Mercy Mode ON 😈📸",
  "Drop That Look — I’m Coming for It 🏹📱",
];

List<String> postUploadPrompts = [
  "Ooooh, juicy material right here 😈🔥",
  "Brace yourself… the roast is incoming 💀📸",
  "Perfect. Now I’ve got ammo 🤣🔪",
  "This face… it’s begging for a burn 😭🔥",
  "I see what we’re working with… yikes 😬📷",
  "Get ready, this one’s going viral 💥🤣",
  "You should’ve stayed in the shadows 👀💀",
  "Oh, we’re going full savage now 😤📸",
  "This is gold. Absolute gold 🏆🤣",
  "Hmm… I see some roast potential 😈📷",
  "Prepare yourself… it’s about to get spicy 🌶️🔥",
  "The people will weep… or laugh 😭😂",
  "I’ve got my eyes on you… and my roast ready 👁️🔥",
  "Yikes. Someone call the fire department 🚒💀",
  "This is gonna be fun… for me 😎📸",
  "Uploading regret? Already happening 😬🔥",
  "Time to turn this into meme magic 🪄🤣",
  "Oh no… the internet is ready for this 😭💻",
  "Face received. Roast commencing immediately ⚡📷",
  "Hold onto your dignity… if you have any 😈🔥",
];
